### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by pviker**
Working on navigation. Need a few basic categories. Thoughts on color
scheme anyone?

### CODE REVIEW

**Comment by Jgrenier91** [comment]
I'm pretty unfamiliar with Github, what am I looking at here?

**Comment by pviker** [comment]
I'm just learning the ropes myself. Basically there's a 'master' copy of the files/project. As we make updates it doesn't change the master copy until the changes are committed. If you go to our main project page:
screen shot 2015-09-27 at 8 47 18 am

You can go to the bottom right where it says "Clone to desktop" 
screen shot 2015-09-27 at 8 48 10 am

You may need the GitHub desktop app for it to work but what that does is create a local copy of our project to your computer. From there you can use your IDE to make changes, etc. After you make changes locally you can use the GitHub app to send a commit of the changes that we can review and choose to accept. 

What I have currently is just the navigation theme that we can maybe use. 

Hopefully that helps. Let me know if you have any other questions.

**Comment by Jgrenier91** [comment]
I've always liked the google material design approach for visuals.

https://www.youtube.com/watch?v=8AkLfYOgIrE - if you're unfamiliar and just
want to understand the concept (this has nothing to do with color scheme so
ignore it if you're uninterested).

As for the color scheme, something like google pushed in their material
design wallpapers -
https://www.google.com/search?q=google+material+wallpapers&es_sm=122&biw=1154&bih=805&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIsreJgcGXyAIVUxSSCh3REQ7l

This is just one idea though and there's no worries if you're not a fan.

**Comment by pviker** [comment]
Awesome. thank you. Experimenting now. Let me know what you think. I also want to change the header bg color if you guys want to play around with it.

**Pull request merged**
